### ISSUE TITLE
Sandbox Authentication

### ISSUE THREAD

**Issue by DomCotton** [giacomelli/SalesforceSharp#17]
Hi,

Is there a way you could modify to allow sandbox authentication?

Thanks

**Comment by giacomelli** [comment]
Hi, 

take a look on the question "How to fix the "expired access/refresh token" error when I call client.Authenticate(authFlow)?": https://github.com/giacomelli/SalesforceSharp/wiki/FAQ

Maybe it can help.

**Comment by DomCotton** [comment]
Hi,

Thanks for the response, i am doing the following:

SalesforceClient client = new SalesforceClient();
var authflow = new UsernamePasswordAuthenticationFlow(ClientIdParameter,ClientSecretParameter,user,pass);
            try {
                client.Authenticate(authflow);
            } catch (Exception ex) {
                MessageBox.Show(ex.Message);
            }

I don't see any ability to change the endpoint?  I see that the SalesForce client class has an InstanceUrl but this is readonly?
Thanks

**Comment by DomCotton** [comment]
OK sorry I see that the TokenRequestEndpointUrl is part of the AuthenticationFlow object, but when i execute now with the test.salesforce.com endpoint i get an Authentication failure.  I have tried with a .test101 appended to the username and without, and no luck!

Thanks

**Comment by DomCotton** [comment]
OK it turned out to be an issue with the setup of the connected app on salesforce, all is working now. Thanks :)
