### ISSUE TITLE
Updating an Account object with Validation Rule using pseudocolumn BillingAddress

### ISSUE THREAD

**Issue by DomCotton** [giacomelli/SalesforceSharp#18]
Hi,

On my salesforce instance i have a validation rule which uses a pseudocolumn "BillingAddress" (not a real field).  When i call client.Update I get the following error:

Validation Formula Invalid (Could not access the following field: BillingAddress. Contact your administrator.)

Do you know if there is any way to make this happen?  I have tried adding BillingAddress to my Account class but it doesn't acknowledge it because it isn't a real column.

Thanks,
Dom

**Comment by giacomelli** [comment]
Try to use  [Salesforce(IgnoreUpdate = true)] attribute on BillingAddress property.

**Comment by DomCotton** [comment]
I am not specifying it, the validation rule was executing on salesforce itself but the error was being returned back.  I tried adding BillingAddress into my Account class but as its not a real field, it failed to read the account object.

Never mind i changed the validation formula, was just an FYI really.

Thanks,
Dom
