### ISSUE TITLE
Object linked fields in SOQL

### ISSUE THREAD

**Issue by DomCotton** [giacomelli/SalesforceSharp#19]
Hi,

Maybe some other day i will try and modify this myself, but it would be nice if you could nest object types to allow for the linkedobject.field ability of SOQL - example:

select Id, Owner.Name from Account

I tried to create a class owner and nest it into account as below:

class Owner {
string Name {get;set;}
} 
class Account {
string Id {get;set;}
Owner owner {get;set;}
}

The workaround will involve duplication of object types unless you can help me out?

Many thanks,
Dom

**Comment by giacomelli** [comment]
Nested object are already supported, but all properties should be public.

Your "owner" project should be changed from private to public access.

**Comment by DomCotton** [comment]
Hi,

I just wrote the class into this comment quickly, in my code i actually have everything public:

 public class Owner {
            public string name { get; set; }
        }

        public class Account {
            public string Id { get; set; }
            public string Name { get; set; }
            public Owner Owner { get; set; }
        }

execution:
var a = client.FindById<Account>("Account", "<id>");

error:
An unhandled exception of type 'SalesforceSharp.SalesforceException' occurred in SalesforceSharp.dll

Additional information: 

SELECT Id, Name, Owner FROM Account WHERE Id = '<id>'

                 ^

ERROR at Row:1:Column:18

No such column 'Owner' on entity 'Account'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.


Am I declaring the object structure incorrectly?  Really appreciate the responses to my questions.

Many thanks,
Dom

**Comment by giacomelli** [comment]
There is a problem with GetRecordProjection method, it is not getting the nested projections.

To workaround until  the fix, you can use Query method and explicit define the projections:
```csharp
var a = client.Query<Account>("select Id, Name, Owner.Name from Account where Id = '<the account id>'").FirstOrDefault();
```

**Comment by DomCotton** [comment]
Many thanks :)  p.s. SalesforceSharp is awesome!!
