### ISSUE TITLE
Auth for Sandbox

### ISSUE THREAD

**Issue by svemoory** [giacomelli/SalesforceSharp#25]
How do I set the instance to sandbox?  Currently 
UsernamePasswordAuthenticationFlow(clientId, clientSecret, username, password) set to  prod by default.

**Comment by giacomelli** [comment]
You need to point to sandbox end-point:  https://test.salesforce.com/services/oauth2/token

More info at the wiki [wiki](https://github.com/giacomelli/SalesforceSharp/wiki/FAQ)
