### ISSUE TITLE
query on custom object results in empty fields

### ISSUE THREAD

**Issue by amsterdammarketing** [giacomelli/SalesforceSharp#33]
When querying a custom object I do get the amount of items but the fields are empty. My c# class  and propeteries are marked public. If I run the example query on the accounts table I get the actual values back. Is there a known bug regarding querying custom objects?

**Comment by giacomelli** [comment]
Hi!

Could you, please, post here your C# class?

**Comment by amsterdammarketing** [comment]
public class Voucher
    {
        public string contact_Id { get; set; }
        public string Trigger_Type { get; set; }
        public string voucherNr { get; set; }
    }

**Comment by amsterdammarketing** [comment]
I've found the cause: the mapping of the __c fields with the fields in the class didn't match. I've renamed the fields in the class and added the __c at the and and now it works. Sorry for this dumb moment!

**Comment by giacomelli** [comment]
Don't worry, it was not a dumb moment at all, could happen to everyone.
I added a note to the FAQ about the suffix for custom objects: https://github.com/giacomelli/SalesforceSharp/wiki/FAQ#q-the-salesforceclientquery-method-is-returning-the-right-number-of-records-but-all-fields-are-null-whats-wrong

Probabbly will be useful to someone else 😉.
